import { NextPage } from 'next';
import Header from 'next/head';

const Head: NextPage<HeadProps> = ({ title }) => {
	return (
		<Header>
			<title>{title}</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			test
		</Header>
	);
};

interface HeadProps {
	title?: string;
}

const defaultProps: HeadProps = {
	title: 'Vangover',
};

Head.defaultProps = defaultProps;

export default Head;
